Make sure a NotImplementedError is always raised on Connection.makefile() (#744)
* Make sure a NotImplementedError is always raised on Connection.makefile

With this patch, code which calls (for example) conn.makefile('rb') will
get a NotImplementedError instead of a confusing TypeError:

    TypeError: makefile() takes 1 positional argument but 2 were given

* ignore any args/kwargs passed